### PR TITLE
Create basic project site #214

### PR DESCRIPTION
**Pull request by Caetan95**
_config.yml URL and baseurl lines are commented, UNCOMMENT them once it is in Indico's repo!!

### CODE REVIEW

**Comment by ThiefMaster** [comment]
You have some commits with a wrong email (`caetan@caetanpc.dyndns.cern.ch`), but since we'll probably squash anyway and cherry-pick into a new gh-pages branch (that has no ancestry from master) this shouldn't be a problem in the end.

Could you enable gh-pages on your fork though so we can preview it via https://caetan95.github.io/newdle?

**Comment by ThiefMaster** [comment]
Regarding the content of the site: I don't think repeating what we have in the README again in detail is a good idea - I would rather focus on what newdle is, and then link to the readme for the install docs

**Comment by Caetan95** [comment]
I am teleworking connected via ssh to my CERN's computer, so the wrong email was because of that (I don't know why though). I did the changes requested, so now is reachable via [https://caetan95.github.io/newdle](https://caetan95.github.io/newdle ) and there is a new content of the site explaining what newdle is

**Comment by ThiefMaster** [comment]
Please rebase your `gh-pages` branch on top of the newdle upstream/gh-pages branch (this just adds an empty config file since a branch cannot be completely empty) and send a PR against the newdle gh-pages branch. That way we can  actually comment on your latest version.

**Pull request closed without merging**
