### PR TITLE
Add import sorting rules

### PR DESCRIPTION
**Pull request by plourenco**
A suggestion for imports that enforces a consistent order.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I like the idea in general, but can we somehow enforce that CSS imports come after everything else? I actually get one of them that eslint can't auto-fix for some reason:

```
[adrian@eluvian:~/dev/newdle/newdle/client:(remotes/petwo/import-sorting) *]> npx eslint --fix --max-warnings 0 src/

/home/adrian/dev/newdle/newdle/client/src/components/creation/timeslots/Timeline.js
  26:1  error  `./Timeline.module.scss` import should occur before import of `./TimelineHeader`  import/order

✖ 1 problem (1 error, 0 warnings)
```

**Comment by plourenco** [comment]
@ThiefMaster 
Agree! Please check if it works as expected now.

**Comment by ThiefMaster** [comment]
image

still seems to put style imports in the middle of other imports in some cases

**Comment by ThiefMaster** [comment]
I like it now :)

Just one small thing which might make the imports look nicer, but I'm unsure which option I prefer... so opinions are welcome:

`"newlines-between": "never"` - this would also get rid of the empty line before style imports, since this cannot be configured per-group

```js
import React, {useEffect, useState} from 'react';
import {useDispatch, useSelector} from 'react-redux';
import _ from 'lodash';
import moment from 'moment';
import PropTypes from 'prop-types';
import TimePicker from 'rc-time-picker';
import {Header, Icon, Popup, Button, Grid} from 'semantic-ui-react';
import {addTimeslot, removeTimeslot, setTimezone} from '../../../actions';
import {
  getCreationCalendarActiveDate,
  getDuration,
  getTimeslotsForActiveDate,
  getNewTimeslotStartTime,
  getPreviousDayTimeslots,
  getTimezone,
} from '../../../selectors';
import {hourRange, toMoment, getHourSpan, DEFAULT_TIME_FORMAT} from '../../../util/date';
import {useIsSmallScreen} from '../../../util/hooks';
import TimezonePicker from '../../common/TimezonePicker';
import CandidateSlot from './CandidateSlot';
import DurationPicker from './DurationPicker';
import TimelineHeader from './TimelineHeader';
import TimelineRow from './TimelineRow';
import 'rc-time-picker/assets/index.css';
import styles from './Timeline.module.scss';
```

or

`"newlines-between": "always"` and removing the `react*` group  - this would split import groups somewhat nicely (with the react group enabled it looks a bit strange IMO)

```js
import _ from 'lodash';
import moment from 'moment';
import PropTypes from 'prop-types';
import TimePicker from 'rc-time-picker';
import React, {useEffect, useState} from 'react';
import {useDispatch, useSelector} from 'react-redux';
import {Header, Icon, Popup, Button, Grid} from 'semantic-ui-react';

import {addTimeslot, removeTimeslot, setTimezone} from '../../../actions';
import {
  getCreationCalendarActiveDate,
  getDuration,
  getTimeslotsForActiveDate,
  getNewTimeslotStartTime,
  getPreviousDayTimeslots,
  getTimezone,
} from '../../../selectors';
import {hourRange, toMoment, getHourSpan, DEFAULT_TIME_FORMAT} from '../../../util/date';
import {useIsSmallScreen} from '../../../util/hooks';
import TimezonePicker from '../../common/TimezonePicker';

import CandidateSlot from './CandidateSlot';
import DurationPicker from './DurationPicker';
import TimelineHeader from './TimelineHeader';
import TimelineRow from './TimelineRow';

import 'rc-time-picker/assets/index.css';
import styles from './Timeline.module.scss';
```

or without removing the react group and changing the pattern to `"{react*,prop-types}",`:

```js
import PropTypes from 'prop-types';
import React, {useEffect, useState} from 'react';
import {useDispatch, useSelector} from 'react-redux';

import _ from 'lodash';
import moment from 'moment';
import TimePicker from 'rc-time-picker';
import {Header, Icon, Popup, Button, Grid} from 'semantic-ui-react';

import {addTimeslot, removeTimeslot, setTimezone} from '../../../actions';
import {
  getCreationCalendarActiveDate,
  getDuration,
  getTimeslotsForActiveDate,
  getNewTimeslotStartTime,
  getPreviousDayTimeslots,
  getTimezone,
} from '../../../selectors';
import {hourRange, toMoment, getHourSpan, DEFAULT_TIME_FORMAT} from '../../../util/date';
import {useIsSmallScreen} from '../../../util/hooks';
import TimezonePicker from '../../common/TimezonePicker';

import CandidateSlot from './CandidateSlot';
import DurationPicker from './DurationPicker';
import TimelineHeader from './TimelineHeader';
import TimelineRow from './TimelineRow';

import 'rc-time-picker/assets/index.css';
import styles from './Timeline.module.scss';
```

**Pull request merged**
