### PR TITLE
Fix elements responsiveness in home page

### PR DESCRIPTION
**Pull request by nop33**

### CODE REVIEW

**Comment by nop33** [comment]
I am not 100% happy with the solution regarding the logo. For a better solution, I need to understand better the reason the middle (empty) column of the header exists:

image

**Comment by ThiefMaster** [comment]
It looks like it's only there for alignment: https://github.com/indico/newdle/blob/master/newdle/client/src/components/TopHeader.js#L24

maybe @panagiotappl remembers

**Comment by nop33** [comment]
If that's the case, I'd rather remove the middle column to give more space for the logo.

**Comment by nop33** [comment]
I included a couple more small and quick fixes. Here's a preview:

image

**Comment by ThiefMaster** [comment]
I just noticed some small issue with inconsistent icon sizes on phone-sized screens only after merging it... any chance you want to do another for that?

image

**Comment by nop33** [comment]
will do!

**Comment by nop33** [comment]
probably just need to add `flex-shrink: 0` to the icon, but I'll test later

**Pull request merged**
